### ISSUE TITLE
How to test CPM model?

### ISSUE THREAD

**Issue by mychina75** [liyemei/caffe-segnet#2]
Thank you for your work.
I noticed that this repository support cpm layers.
How can I use to test my cpm model? Are there c++ interface?
Thanks

**Comment by liyemei** [comment]
@mychina75 
you can references : https://github.com/CMU-Perceptual-Computing-Lab/caffe_train
sorry,there is no C++ interface.I only provide the compilation of CPM layer,but  you can wirte a matlab 、 python  or C++  code to test your cpm model.

**Comment by mychina75** [comment]
Thank you for your reply. I will close it.
